apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 224425920035.dkr.ecr.us-east-1.amazonaws.com/photo-gallery-frontend:local
          ports:
            - containerPort: 80
