name: Deploy App to EKS

on:
  push:
    branches: [main]
    paths: [k8s/**, Task-Project/**]

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name photo-gallery-eks-cluster --region us-east-1

      - name: Get EKS Node Public IP
        id: nodeip
        run: |
          NODE_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:eks:nodegroup-name,Values=photo-gallery-eks-cluster-node-group" \
                      "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].PublicIpAddress" \
            --output text)
          echo "NODE_IP=$NODE_IP" >> $GITHUB_ENV

      - name: Inject public IP into React .env
        run: |
          echo "REACT_APP_BACKEND_BASE_URL=http://${NODE_IP}:30081" > Task-Project/client/.env
          cat Task-Project/client/.env

      - name: Build React App
        run: |
          cd Task-Project/client
          npm install
          npm run build

      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
